### ISSUE TITLE
Head scripts component included between <head> and <body> tags.

### ISSUE THREAD

**Issue by GregWisniewski** [mediablox/mb.mbfw.pro#1]
`src/html/partials/inc/scripts-head.njk` file is being included in the main layouts file `src/html/layouts/layout.flex.njk` is being rendered between the **<head>** and **<body>** tags.

The scripts should be included within the **<head>** tag.

**Comment by DeanJMorgan** [comment]
This issue is now resolved and merged into the main branch.

I am closing this issue.
